### ISSUE TITLE
Tries to use a TVDB association when it is a movie

### ISSUE THREAD

**Issue by speedello** [japanesemediamanager/ShokoServer#13]
**Reported by Craige1Emmott, May 28, 2012**

Simple check to see if the anidb anime type is a move/series/special/ova to check whether to use the tv db or the moviedb.

**Comment by celcius01** [comment]
By 'done', can i know what exactly do you mean? I remember last time asking something like this though, where if it is a movie, it will take the info from moviedb to show in the episode overview. I guess this isn't it?

**Comment by jmediamanager** [comment]
Yeah that's what it is. Is it not working for you?

**Comment by celcius01** [comment]
Umm... no i guess? Here's an example:
![jmmd movies](https://cloud.githubusercontent.com/assets/9668999/5771818/d0b688dc-9d80-11e4-9f58-da019ec91c79.PNG)

The moviedb link was connected manually by me. Actually, all standalone movies moviedb link was manually connected by me (by all i mean those downloaded after i changed over to beta release).
And as you can see, no episode overview and i just checked the moviedb link for that and it does have a description.
Is it suppose to be like this?

**Comment by jmediamanager** [comment]
You won't get any episode images, but the fanart should display.
Look at the images tab to see if it has downloaded anything, if you you might need to refresh the info

Here is Mine

![snap8](https://cloud.githubusercontent.com/assets/6645153/5794366/5eb6f844-9fbe-11e4-997b-8e5cd2452096.jpg)

![snap10](https://cloud.githubusercontent.com/assets/6645153/5794370/62920238-9fbe-11e4-885b-941a7ceb0e19.jpg)

**Comment by AreFinstad** [comment]
this have always bothered me about JMM, it should be able to use the fanart as a thumbnail in the worst case, just to use the wasted space and fill out the pages.
could make it so if there isnt a thumbnail at all for any file episode or movie or whatever then it should use the most popular fanart or a fanart the user set for that group.

i think this sounds like a good idea and a middle ground, its not like people cant upload thumbs or pictures themself for MDB and so on either to use this.

**Comment by celcius01** [comment]
Ah, the images? If that's it then yeah i got it. I hope im not being picky here but yeah what Arefin said was kinda nice to have. Using the fan art instead of that 404 chick.
