### ISSUE TITLE
Sync from JMM to AniDB

### ISSUE THREAD

**Issue by Stonedestroyer** [japanesemediamanager/ShokoServer#137]
I know you can sync mylist so it takes information but is there a way to force it to sync jmm information to anidb if it's outdated?

**Comment by AreFinstad** [comment]
this is needed IMO. many times my server access queue is too large for me to bother waiting esp when its super slow and dont want to wait forever.

better to let us be able to choose when to sync the library on our server with our user when we want as it will free up the user to do what they want and feel like without being bound to let the queue go on forever and ever.

**Comment by misakitchi** [comment]
When i clic on "Sync MyList" its update the files i have AND wachted status on AniDB? Or Only the files i have?
And its "JMM => AniDB" OR "JMM <= AniDB" OR "JMM <=> AniDB" ?

**Comment by ElementalCrisis** [comment]
This needs clarification, making a note and tagging @japanesemediamanager/developers.

**Comment by hidden4003** [comment]
It will add local files that are not added yet and check watched states if it sees watched anywhere it will update the other side.

shoko = watched, anidb = unwatched  -> anidb will be updated to watched
shoko = unwatched, anidb = watched -> shoko will be updated to watched
file is in my list but shoko doesn't have it - file is ignored

Hope this helps.

If you prefer to look at the code yourself then follow this link: https://github.com/japanesemediamanager/ShokoServer/blob/master/Shoko.Server/Commands/AniDB/CommandRequest_SyncMyList.cs#L37

**Comment by bigretromike** [comment]
hope it wont desync when you set unwatched (when both was watched) on one side and then sync ;-)

**Comment by ElementalCrisis** [comment]
It should depend on your settings.

![image](https://user-images.githubusercontent.com/9443295/27768739-8f1763de-5ecf-11e7-8f54-e7e342564293.png)
