### ISSUE TITLE
questions about linux support and such.

### ISSUE THREAD

**Issue by AreFinstad** [japanesemediamanager/ShokoServer#138]
so i im getting a "bit" tired of problems with windows and with it failing to activate legal versions of the OS (that they cant even bloody help me with) and im really thinking about jumping ship here and get something on the Linux platform (tho not sure which one just yet))

the questions is tho, can i  just run JMM with Wine like other apps/games or will it have problems with the sql bases and such? i guess in the worst case i can run a virtual machine for it and it will be fine.

the only thing keeping my on Windows is JMM and some games and those get more and more ports now with newer titles is getting released on the platform on day one aswell (heck they even said today that they are porting the old Batman Arkham Asylum game.... so more will come)

the only thing left is really JMM as games get sorted out more and more and Wine has less problems with them then they did aswell. 

anyone used linux at all before with JMM and what way did you use it? had issues with it?

i know alot of the software is windows based with JMM but there got to be a way to use it without dualboot (want to be able to use the normal OS while JMM is running is the key here)

**Comment by AreFinstad** [comment]
well comming back to this issue i can say Linux is alot more issues than its worth in my Eyes. tried it for less than a week and it was nothing but a hassle on my part. NTFS mounting is a hassle and installing small things was more issue than good then doing it on Windows. after trying and using Ubuntu a few days trying to get the drives and such running i didnt bother at the end with all the extra hassle and lack of app support for my sake. wasnt for me and wont touch it again, i myself is better off with Windows.

i recall my interest in Linux..... maybe as a pure Media Server it can work for me, more than that is a no, sticking to Windows here.

**Comment by CatmanIX** [comment]
Maybe you should close this issue then if your questions have all been answered/dismissed?

**Comment by bond4u** [comment]
Has anyone tried running JMM Server on Raspberry Pi?

**Comment by AreFinstad** [comment]
using it might be smooth but whenever it would update its metadata and so on it would just struggle i would think.
and dont get me started when it needs to hash the files itself.
it could work but all CPU intensive tasks would be slow as it gets.
in my mind its not viable at all, but i like speedy performance, and JMM is already slow ATM.

**Comment by bond4u** [comment]
Some Android boxes have loads of cores, they could be flashed with linux perhaps?
Basically, I would like to remove JMMserver from my windows gaming desktop.

**Comment by bmfrosty** [comment]
@bond4u

The fun thing about Android is that underneath it all, it's linux.
