### ISSUE TITLE
[TIPS] Reduce JMM/SQL Memory Usage!

### ISSUE THREAD

**Issue by misakitchi** [japanesemediamanager/ShokoServer#158]
Hi! Its not an error/issue but tips to reduce memory usage :)

Before JMM(Server+Desktop)/SQL was using almost 2.5Go of memory!!!!
Now its use 800Mo!!!!! ^_^

SQL:
SQL Server Management Studio, then Server Properties, and Memory, put 256Mo for max memory
Before that SQL was using up to 1.1Go!!! Now only 380Mo :)
You can try less than 256Mo but JMM was no more working...

And i love 64bit but i use so much memory! :(
So i use a tool to force 32bit mode in JMM Server and Desktop: CorFlags
You can find it there:
C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\Bin\x64

Copy corflags.exe in JMM Server and JMM Desktop folders
And use thoses commands lines

JMM Server: CorFlags jmmserver.exe /32BIT+
JMM Desktop: CorFlags jmmdesktop.exe /32BIT+ /Force

Voila! ^_^

PS: if you can put all tips somewhere its a good idea...

**Comment by ElementalCrisis** [comment]
Recent work has reduced Shoko Server's memory footprint, I'm going to close this issue.
