### ISSUE TITLE
MediaBrowser 3 support

### ISSUE THREAD

**Issue by saitoh183** [japanesemediamanager/ShokoServer#16]
In Mediabrowser 3 there is currently a plugin for Anime and it works great overall but JMM offers lots when it comes to anime and maybe could maybe enhance the current Anime plugin or replace it :)

**Comment by ElementalCrisis** [comment]
Support for Emby is something that we will not be adding ourselves, this doesn't mean we don't want to see it supported but adding another plugin that requires us to support and maintain it is beyond the scope of the project at the moment. 

Similar to Nakamori, we'll provide support if another developer wants to create the plugin.
