### ISSUE TITLE
Adding custom settings to .config file

### ISSUE THREAD

**Issue by bigretromike** [japanesemediamanager/ShokoServer#216]
Adding setting to .config file at beggining of <appSettings> resolve in rewriteing config file and deleting custom tag. 
Adding it at the end of <appSettings> resolve in accepting it.

Order shouldn't matter

**Comment by da3dsoul** [comment]
I'm not sure what this was about. I'll close it for now, reopen if there's a reason.

**Comment by bigretromike** [comment]
If way issue with adding new setting via hand to config file (non-json if i recall). If you add something as first line it would act as corrupt config and rewrite it, but of you add new setting at bottom of file the it woild accept it

**Comment by da3dsoul** [comment]
Ah, well fixed
