### ISSUE TITLE
Having the exact same file in two different import locations results in an import loop

### ISSUE THREAD

**Issue by miracle152004** [japanesemediamanager/ShokoServer#235]
I had the same file in two different import locations.
This resulted in the issue, that the server removed one file the first import.
The other file the next import
and so on.

I think the duplicate files should be included into the hash algorithm to prevent that they swap each other over and over again.
Also the duplicate file situation should be more visible in the server. I had to attach a debugger to know whats going on.

**Comment by bigretromike** [comment]
Last time I had this issue on stable end up not moving the duplicate from drop folder. 
Are you using drop/source folder ?

**Comment by da3dsoul** [comment]
Well, if you are using drop folders properly, it shouldn't happen at all anymore

**Comment by bigretromike** [comment]
what do you mean by properly ?:-)

**Comment by da3dsoul** [comment]
1 source, 1 destination, at least the source watched. There is better and additional handling in dailies. I only use 'stable' for a day or so until I make more commits.

**Comment by bigretromike** [comment]
whats wrong with using multi sources ? So this is fixed in daily ?

**Comment by da3dsoul** [comment]
With more than one source, you introduce multi processing, and our system doesn't know how to deal with it. If you know they won't have files dropped at the same time, go for it.

**Comment by da3dsoul** [comment]
I haven't tried, but it's probably fixed

**Comment by ElementalCrisis** [comment]
I meant to reply to this issue, I tried earlier this week and the duplicate file was not moved.
