### ISSUE TITLE
Adjustable delay for hash after import

### ISSUE THREAD

**Issue by da3dsoul** [japanesemediamanager/ShokoServer#237]
I often find that things are hashed incorrectly because JMM started hashing them before they are finished moving into the source folder. It can just be a setting with the option in desktop, but this one actually should have it in server as well.

**Comment by da3dsoul** [comment]
The ideal is just that it won't scan a file until it is finished moving, but other than delay, I'm not sure the best way to check that.

**Comment by maxpiva** [comment]
I'm maybe wrong but jmm will get a permission io exception when it tries to
hash a moving file. Until the copy is finished the hash will be not
calculated. If you have wrong hashes do a memcheck.

**Comment by da3dsoul** [comment]
It won't hash if it tries the file source, but it'll have no problem if it tries to hash a file that is is going to be there.

**Comment by maxpiva** [comment]
Let's redo. I'm pretty sure when moving a file there is a lock read on the
destination file. Which means if other thread or process try to read it it
will get an exception. Also if the harsher started to hash a file you won't
be able to move that file till the end of the hash. Because there will be
an open handle to the file pending.

**Comment by da3dsoul** [comment]
I see, that may or may not be the case, but either way, I often need to rehash things in a drop source

**Comment by jmediamanager** [comment]
Just to confirm, when you rehash does the ED2K hash actually change?

It may be just that no-one has entered the file into AniDB yet.

**Comment by da3dsoul** [comment]
Yes, it is actually rehashed

**Comment by da3dsoul** [comment]
One thing I think it might be is when it tries to hash a downloading file, it'll eventually give up and move on. Then, I just rehash it later when I know it's done (before I set up drop folders, I set up my RSS feeds to sort shows properly). It might detect the lock and go to the next file without ever hashing the file properly.

**Comment by da3dsoul** [comment]
Here's some examples:
[HorribleSubs] Hundred - 04 [720p].mkv
Hash: 122C64A9CC4C6FA3F296D4866A961A97
CRC: 7A5F787A

[HorribleSubs] Seisen Cerberus - 04 [720p].mkv
Hash: 9861F85F3246514C4C34F0267DF24D08
CRC: 96553D3C

[Underwater-µtw] Ajin - Demi-Human - 13 [932DD38B].mkv
Hash: 75EFBA4BDF211E19A6D678A52F30D7BB
CRC: 02950104

Ajin is the best example as it has the CRC in the name, which doesn't match. Rehashing fixes it.

**Comment by jmediamanager** [comment]
have you got your drop source folder in JMM set to the same location as the downloading folder in your torrent client?

**Comment by da3dsoul** [comment]
Nope, move on completed. ![screenie](https://dl.dropboxusercontent.com/u/31454410/Github%20Issues/Screenshot%202016-04-25%2022.12.50.png)

**Comment by maxpiva** [comment]
da3dsoul be a champ and do a memcheck on your machine. Just in case.

**Comment by maxpiva** [comment]
I have no access to git or Visual Studio right now, (Machine formatted).

jmediamanager

Could you add a simple check before checking...

Do a File.Open with FileShare.None, and then a stream Close , before
hashing. If it throws an exception someone else have an open handle to the
file.

**Comment by da3dsoul** [comment]
Running a memcheck now. I'm going to work, so I'll check the results later.

**Comment by da3dsoul** [comment]
memcheck is fine. Nothing wrong with my RAM, which I'd hope considering I bought it only 5 months ago.

**Comment by jmediamanager** [comment]
@maxpiva ok will give it a go

**Comment by bigretromike** [comment]
@maxpiva I'm not sure if there is lock while moving files. Maybe on specific configuration. But maybe it was fixed in 2016?
@da3dsoul
Especialy now when its cross-platform. 
But making delay will be hard consider:
1. we dont know the size of file
2. we dont know how its being copied (network/local)
3. we dont know if its only file that being copy
4. constant delay would be a miss shot with big/slow copy.
Any ideas, how to resolve it ?

**Comment by da3dsoul** [comment]
Fixed already
