### ISSUE TITLE
If the hasher is aborted due to file access timeout, don't add it to the database

### ISSUE THREAD

**Issue by da3dsoul** [japanesemediamanager/ShokoServer#247]
The hash won't be correct as it didn't happen, and the file just sits in "unrecognized" until you notice and rehash it. If it isn't there, the importer will rescan it later.

**Comment by bigretromike** [comment]
@da3dsoul what about this one ? This one is fixed too ?

**Comment by da3dsoul** [comment]
Nope, gimme a sec, I'll do it now
