### ISSUE TITLE
Fix local episode count for Kodi

### ISSUE THREAD

**Issue by da3dsoul** [japanesemediamanager/ShokoServer#374]
It never really worked for me, I don't what the issue was. Basically, it should count specials and episodes, but not trailers or credits.

**Comment by maxpiva** [comment]
Maybe we should add 4 fields to the serie, like episodeCount specialCount
trailerCount creditCount, and leave the Plex with the current episodecount

**Comment by da3dsoul** [comment]
That's fine, simple addition isn't hard to implement. I want it to tell me if I haven't watched an ova, but I don't care about trailers, etc
