### ISSUE TITLE
Raiting for some of series inside newly added is wrong

### ISSUE THREAD

**Issue by bigretromike** [japanesemediamanager/ShokoServer#400]
https://github.com/bigretromike/nakamori/issues/162#issuecomment-245821407

the rating is 3 digit without dot, but should be divide by 100

**Comment by da3dsoul** [comment]
This can prolly be closed

**Comment by bigretromike** [comment]
could you point which commit fix this ?

**Comment by da3dsoul** [comment]
Idk but we use APIv2 now

**Comment by bigretromike** [comment]
oh.. I see

ok, lets close this as it could been shoko issue and its been few months now, and they probably fix it.. or not. we will see in future

**Comment by bigretromike** [comment]
It could have been deeper issue than api, but i close this then as there was no respond to it anyway...
