### ISSUE TITLE
Sync Mylist from anidb results in Ban

### ISSUE THREAD

**Issue by miracle152004** [japanesemediamanager/ShokoServer#405]
Hi I am getting a strange result.
When the JMM Server tries to start the Sync of the Mylist of Anidb the Server shows the "Banned" Message in the client is shown, but in the logfiles there is no entry for this error, just the Info that the mylist sync ist starting.

Could you please take a look?
Thanks.
Best regards miracle152004

[2016-09-09.txt](https://github.com/japanesemediamanager/jmmserver/files/464770/2016-09-09.txt)

**Comment by ElementalCrisis** [comment]
Its there, multiple times.

> [2016-09-09 03:00:32:670] Info|AniDBHTTPCommand_GetFullAnime.Process => AniDBHTTPHelper.GetAnimeXMLFromAPI => JMMService.LogToSystem AniDB HTTP - Getting Anime XML Data From ANIDB: 11875
[2016-09-09 03:00:33:440] Info|AniDBHTTPCommand_GetFullAnime.Process => AniDBHTTPHelper.GetAnimeXMLFromAPI => JMMService.LogToSystem AniDB HTTP - Got Anime XML Data From ANIDB: 11875 - 769,4579 - <error>Banned</error>

Are you doing anything else like importing or running other AniDB commands?

**Comment by miracle152004** [comment]
Hi,
everything before 2016-09-09 08:40:19:400 was the old version (v3.4.6.4) which was showing this error in the UI and logging this error. I thought maybe this error was due to using an old version so I switched to the new version v3.6.1.0.

But the new version was still showing this error in the UI, but the log entry was missing.

I was importing files but not really much. Around 15-20. After deactivating the mylist sync in the settings I was able to finish the import without trouble.
Also after showing the banned message I tried logging in which webaom which worked and then I tried continuing the General Tasks which paused and showed the banned message again.

**Comment by ElementalCrisis** [comment]
Yeah the 2nd time you probably got yourself banned for using AoM and JMM at the same time.   I wonder if the AniDB commands are executing as normal in their timer but sine your still importing its triggering the ban.

**Comment by miracle152004** [comment]
Hi I wasn't using it at the same time.
I was using JMM, banned message popped up.
I started webaom, locked in, cached 1 file successfully, locked out, waited 1 minute and resumed the "General Tasks" in JMM. Banned Message Pops up again.

The JMM Desktop AniDB Connection test also worked without problem.

I will test it again tomorrow and identify if this is still an issue or maybe it was some kind of other error. Which resulted in the ban message showing up in the UI.
But if the message pops up at least there should be a corresponding log entry in the logfiles.

**Comment by hidden4003** [comment]
Looks like one more http ban.

**Comment by miracle152004** [comment]
Hi,
I tested it now for four days and it did not happen again.
So maybe it was something that happened on those days.
Maybe it was a different error which were misinterpreted.
I do not know.

So for the meantime I think you can close this issue.

Thanks.

**Comment by da3dsoul** [comment]
I don't know why this was reopened. I'm closing it for now. Open if it's an issue
