### ISSUE TITLE
Ability to get more info on torrent results

### ISSUE THREAD

**Issue by jmediamanager** [japanesemediamanager/ShokoServer#41]
**Reported by Craige1Emmott, Jan 14, 2013**

Look at pulling descriptions, comments, etc from websites for torrent results. Might need to look at a scraping script system. Such a system should allow for easy expansion to the download sources.

**Jan 15, 2013 imperialxt**

This will need different scraping for each site? and is it really necessary? the file title for anime torrents should be informative enough.

**Jan 16, 2013 Craige1Emmott**

The four main use cases I see for this are:
1. Pulling info for use in other systems, e.g. enables "safe" searching based on anime categories. There are probable other systems that could benefit from that data as well
2. Allows for users to see the quality of a torrent(comments, file sizes, resolution, rip source, etc). Saves waisted download quotas. 
3. A fair amount of anime have anime relations that show up in search. It would make it easier to tell what they are (is it the sequel that people should watch first?, etc)
4. Allows for new download sources to be added easily, as well as updating old sources if needed.

**Comment by ElementalCrisis** [comment]
1. The sites JMM uses are trustworthy when it comes to anime.
2. Agreed, more info would be beneficial.
3. Only a few sites do this, AniDB already does this.
4. New download sources can be added by searching.

**Comment by ElementalCrisis** [comment]
As torrent support is no longer a feature of Shoko, I'm closing this.
