### ISSUE TITLE
Drop Folders Don't Overwrite Files

### ISSUE THREAD

**Issue by bigretromike** [japanesemediamanager/ShokoServer#444]
If I drop folder with full series and one with just a vol, then the vol items arent moved to output folder - probably because of same name/hash. Can we move those (overwrite) destiny or delete duplicates from source?

**Comment by da3dsoul** [comment]
Drop folders don't overwrite files. If they are duplicated, then delete them. If they are just the same name, use the rename utility or something so they aren't. We don't rename files unless the user has it set, and we let the user handle multiple copies of the same episode.

**Comment by bigretromike** [comment]
It dont delete them. 
Also when I put something in input folder the logical way would be: As JMM see what it is it recognize it, but instead it treat it as not recognized (same as it wouldn't find it in anidb because it leave it there)

**Comment by da3dsoul** [comment]
That's how it treats multiple copies. It isn't supposed to delete, rename, or anything by itself. Use the utility for multiple files to resolve them. JMM does not support multiple files for the same episode at this time (and I don't think anyone has plans to).

**Comment by bigretromike** [comment]
sure is it the intended way ? As I have same file in collection it should delete recognized duplicate file if its inside drop folder - because it how it works now, it dont recognize it as duplicate if it is in not destination folder in this case - Im talking just about Source/Destination Folder case - I dont care about duplication in full collection as that is coverd by utility as you said

**Comment by ElementalCrisis** [comment]
Ideally if it's a duplicate file, it should just add a "1" to the end of the filename and then the user can delete them in Desktop.

**Comment by bigretromike** [comment]
Both are logic imo, and yours is the simplest solution - as when jmm find series it move it to output folder which is the ideal thing. 

Also adding number to filename before extension ;-)

**Comment by bigretromike** [comment]
I will try to add this functionalyty to make it the best logical way
If jmm know the series and its already in output folder add number (iterated) to end of file name (without extenstion) and move it to proper folder

**Comment by ElementalCrisis** [comment]
I was looking in the code for something else and came across this in VideoLocal_Places.cs

``FileSystemResult<IObject> dst = f.Resolve(newFullServerPath);
                if (dst.IsOk)
                {
                    logger.Trace("Not moving file as it already exists at the new location, deleting source file instead: {0} --- {1}",
                        this.FullServerPath, newFullServerPath);``

Your file should be automatically deleted if it already exists in the DD.

**Comment by bigretromike** [comment]
But its not, or thisis new 

On September 30, 2016 1:42:56 PM GMT+02:00, ElementalCrisis <notifications@github.com> wrote:
>I was looking in the code for something else and came across this in
>VideoLocal_Places.cs
>
>``FileSystemResult<IObject> dst = f.Resolve(newFullServerPath);
>                if (dst.IsOk)
>                {
>logger.Trace("Not moving file as it already exists at the new location,
>deleting source file instead: {0} --- {1}",
>                        this.FullServerPath, newFullServerPath);``
>
>Your file should be automatically deleted if it already exists in the
>DD. 
>
>-- 
>You are receiving this because you were assigned.
>Reply to this email directly or view it on GitHub:
>https://github.com/japanesemediamanager/jmmserver/issues/444#issuecomment-250724359

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by ElementalCrisis** [comment]
That's been there for awhile so we probably need to trace it and find out why it's not working.

**Comment by bigretromike** [comment]
I inspect code. It was moved to different place + it had little refresh by Max, and for testing in latest git version it does work.
Also there is trace like you mention - I only dislike the delete of file is made but probably someone want to stick with "custom class" for that - most important thing is it work ok.
It could be also the class problem as this function use

```
FileSystemResult fr = source_file.Delete(true);
```

After release 3.7 - we should test it and if that async task make problem we could allway put try {} catch{} with File.Delete and File.Exist closure.

**Comment by bigretromike** [comment]
Currently Im unable to reproduce it but Im unsure if this is thanks to fix for #445 or by not having right input.

**Comment by maxpiva** [comment]
The original JMM behavior is delete the file, the file is duplicated,
exactly the same file, since they have exactly the same hash. This only
happens off course if the Import Folders are in the same filesystem
(Local<->Local) (Amazon<->Amazon), etc.

**Comment by bigretromike** [comment]
The problem is that there are some fluctuation from that behavior. 
It looks like that at random time it wont delete it.
Before - as me (3.6.1.0) and @da3dsoul (3.7.0.0) noticed. 
It so random that I wasn't able to reproduce it while more than hour of testing - maybe its depend of async/task queue or time of querying db. dunno..

**Comment by da3dsoul** [comment]
I've not had this issue in weeks now. I'll close it and we can reopen if it becomes a thing again
