### ISSUE TITLE
Drop Folders Don't Always Delete Empty Source Folder

### ISSUE THREAD

**Issue by bigretromike** [japanesemediamanager/ShokoServer#445]
Sometimes input folder when importing series import it correctly but leave folder behind.
Its very rare case but happens. 
Also the folder dont have any hiden files.

**Comment by da3dsoul** [comment]
I have also encountered this.

**Comment by ElementalCrisis** [comment]
Hmm, maybe a permissions issue? I've never encountered this issue on my end. We could add a check that scans folders inside a Drop Source and if the folder is empty then delete the folder.

**Comment by bigretromike** [comment]
not a permission issue, as jmm is runnung as admin and current user without admin can delete that folder.

We could add watchdog that clean it or just pin point problem ;-) as its not only on my setup...
My folder setup is:
main anime folder
input folder
drop folder > that in the end i copy onto main folder
and alot of same files (exact names) :-) maybe when it find same file in output folder it break list or something or badly iterate on left over folders

**Comment by bigretromike** [comment]
@da3dsoul did you encounter it in 3.7.0.0 ? or in 3.6.1.0?

**Comment by da3dsoul** [comment]
Both

**Comment by ElementalCrisis** [comment]
I've re-opened this issue as now every time Server moves a file, it's leaving the old folders and not deleting them.

**Comment by ElementalCrisis** [comment]
@bigretromike Can you double-check this? Fresh install and empty folders are being left behind.

**Comment by da3dsoul** [comment]
Verified, I have empty folders everywhere

**Comment by bigretromike** [comment]
The problem was that empty folder was there. If folder is empty it should be deleted. If there is folder inside Source then it contain non index-able items.

**Comment by ElementalCrisis** [comment]
Here's the test I did a couple weeks ago. I had a series in a folder and moved it into my DS, the files were moved into my DD but the folder, which was not empty was not deleted. I'll check again when I get home and see if the logs has any additional info.

**Comment by da3dsoul** [comment]
This is closed because I fixed it

**Comment by bigretromike** [comment]
Ok, I saw you both wrote that "empty folder" left in DS. 
And didn't reopen as I wanted confirmation that the main problem wasn't inverted from the original issue

**Comment by ElementalCrisis** [comment]
Nice, awesome work @da3dsoul.

**Comment by da3dsoul** [comment]
I get it. I should've noted, but I had finished a binge and didn't care enough at the time. The commit says it's fixed...somewhere
