### ISSUE TITLE
Update Client to Use nancyfx Only

### ISSUE THREAD

**Issue by da3dsoul** [japanesemediamanager/ShokoServer#446]
JMM Desktop can either be moved to the /api prefix and we can expand it as needed, or we need to port the servicehosts to nancyfx.
- [x] JMMServerBinary
- [x] JMMServerImage

People may edit this to add other necessary changes.

This is in Server as either way, we will likely need to change the server first to accept it.

**Comment by bigretromike** [comment]
Max asked me to make nancy like calls for client some time ago and said he eventualy move to that as it most of time same naming etc, and thst is inside binnary file in api. Currently im unknow of situation as we all agree that 'binnaryblob' should be drop out anyway

**Comment by da3dsoul** [comment]
Yeah, but JMM server image needs done. I've been working on it, but for some reason it throws 404 even on proper input

**Comment by bigretromike** [comment]
/image/ was up and running, so you could hoop that up

**Comment by bigretromike** [comment]
Client use JMMServerImage2 as its a nancy implementation and it was pushed here: https://github.com/japanesemediamanager/jmmclient/tree/nancy
