### ISSUE TITLE
StartUp issue

### ISSUE THREAD

**Issue by Rand-Random** [japanesemediamanager/ShokoServer#467]
Upon startup I am getting the following message:

![image](https://cloud.githubusercontent.com/assets/9868626/19220772/5d452780-8e35-11e6-813c-67320606135e.png)

I than started the app again as normal user so more or less ignoring the message, but on a second start the message doesnt appear again.

The problem is that the boolean migrate gets populated with 
bool migrate = !Directory.Exists(ApplicationPath);

So for all Users running the JMMServer for the very first time this is always true and if I am not admin the code Application.Current.Shutdown() run and the app will shutdown at some time, not immediatly to terminate immediatly we would need to call Environment.Exit(-1).

Since it doesnt terminate immediatly the app continues and loads the MainWindow in there a log is getting written and when a log is written it creates the JMMServer directoy in ProgramData.

With that starting the JMMServer again will result in the migrate boolean being false and so no Admin is required, since its a fresh install and all MigrateDirectories never said ShouldMigrate to begin with.

So the basic question is:
Why would we want to migrate simply if the JMMServer directory is missing in ProgramData?

A more advanced question:
After that message I am getting another message telling me to run as Admin
![image](https://cloud.githubusercontent.com/assets/9868626/19220862/82edc512-8e37-11e6-9b37-5c09e7752b6e.png)

How about we make a little console application that holds all the stuff that needs elevated priviledges and start that with an argument what code should execute?

For example "JMMServer_AdminHelper.exe /migrate" and "JMMServer_AdminHelper.exe /firewall" or something similar.

**Comment by ElementalCrisis** [comment]
You need to run it as admin so it can properly migrate which is why you get the second error. 

This was brought up before and I thought we fixed it so it wouldn't do anything if run as a normal user no matter how many times you restarted it.

**Comment by Rand-Random** [comment]
Just for clarification since I believe there is a sort of misunderstanding the 2 messages arent related and are produced by two different code parts in JMMServer startup routine.

The first one is the migrating the JMMServer settings for the config file in the program directory to the programdata directory and the second message is for the firewall settings.
I do believe the fix you mention was about the second message with the firewall setup and not about the first message (which is unrelated).

Also it doesnt really matter that it does something since the only thing it does to prevent the first message from appearing a second time is creating a dictionary, which in my opinion should happen anyway and be no condition for the migration dialog, since as I mentioned its the first run of the JMMServer on a fresh install so nothing to migrate here but the code says migrate is true if the folder is missing but folder is missing since it the first run.

**Comment by ElementalCrisis** [comment]
Ah OK, I missed the fresh install part. 

Your right, a fresh install should not see the migrating message as it should silently create the files in programdata, not create then move.

**Comment by SubaruSumeragi** [comment]
I have the same problem with when I upgrade from 3.6.1.0 even after the first run as administrator.

**Comment by da3dsoul** [comment]
First part or second? They are two different solutions

**Comment by bigretromike** [comment]
this was fixed with both setting location pick up and jmm server detection.
Only thing that is needed is to delete setting.js from shoko folder that was created broken when it didn't have those patches.
