### ISSUE TITLE
After Migration error

### ISSUE THREAD

**Issue by bigretromike** [japanesemediamanager/ShokoServer#485]
My migrated settings.json and other files inside ProgramData/JMMServer are own by "administrator" account and not mine account - probably thanks to running is as Administrator in some point of time.
Also the JMMServer folder is own by admin account. 
This result in error (its full error as the Dialog Windows cut it there):

```
System.UnauthorizedAccessException: Access to the path 'C:\ProgramData\JMMS...
Error Loading Settings:
```

Shouldn't settings be in /Users/User/AppData/Roaming ? As it would be JMMServer settings per User?

**Comment by da3dsoul** [comment]
Settings yes, but the rest, no

**Comment by da3dsoul** [comment]
Generally you don't need to sync server settings as you are not running a server on any old computer

**Comment by bigretromike** [comment]
I assume rest also as You could have different db in both settings and that would end up with wrong images.

**Comment by da3dsoul** [comment]
I think this can be closed. I've not had any issues, and migration seems to be working for many, if not all of the beta testers

**Comment by ElementalCrisis** [comment]
If any Server related migration issues pop-up we can re-open and investigate.
