### ISSUE TITLE
[DEV] Missing local files no longer recoginzed (Cache)

### ISSUE THREAD

**Issue by t0815** [japanesemediamanager/ShokoServer#490]
Seems, due to file caching, the client displays no longer an info (orange exclamation mark) if
local file does not exists anymore but db entry is still there.

Clicking the 'Play' button on non existent file will result in following error:

![image](https://cloud.githubusercontent.com/assets/10379828/19629101/445dcdec-996d-11e6-8505-e5f3245b6bda.png)

Running the 'remove missing Files' command still removes the files from DB. 

Maybe add a fileexists check on server, even for querying file data from cache. It wont have impact on speed too i guess.

**Comment by t0815** [comment]
to further explain the issue maybe:

![image](https://cloud.githubusercontent.com/assets/10379828/19737334/51430bd8-9bb3-11e6-8dcc-e93bba2141ab.png)

The first file has been removed from disk (manually, not via JMM), but is still marked as being available.
Deleting the file in JMM (the already missing file) is not possible too, there i get a propper error message:

![image](https://cloud.githubusercontent.com/assets/10379828/19737405/a3945932-9bb3-11e6-8df6-0153a3972575.png)

But i cant remove it from DB there (not even if i deselect local filesystem provider).

**Comment by ElementalCrisis** [comment]
Unless I'm reading this wrong, @da3dsoul recently fixed this. Closing but please let us know if you encounter this issue again.

**Comment by da3dsoul** [comment]
This should be fixed now. We'll see.
