### ISSUE TITLE
Switch several default filters to 'Apply at Series Level'

### ISSUE THREAD

**Issue by da3dsoul** [japanesemediamanager/ShokoServer#501]
@japanesemediamanager/developers I want to discuss this. I'll start by saying a few that I think should definitely be series level:
Years - Currently, it seems there is a bug in which it only takes the first year in a group, causing confusion.
Continue Watching - This one could stir some debate, but I think it should return only the series
Newly Added Series - Not as important, but I believe should be series level.
TvDB Link Missing - I'm changing this one anyway. Sorting through groups to fix one series is a pain.
Votes Needed - I'm changing this anyway. Same reason.
Missing Episodes - I really think it should be, for the reason above. It's up for debate, though.

Note: The ones I am changing without discussion are not Locked Filters, and I'm only changing the default, so if you don't agree, change it (or ignore it if not on fresh db) in Desktop.

There are some that should be talked about purely due to usage:
Tags
Recently Watched
Newly Airing Series

**Comment by da3dsoul** [comment]
https://github.com/japanesemediamanager/jmmserver/commit/76afb3a07e8d5add4c6fc094e65cf7bbfa76a0cb

**Comment by ElementalCrisis** [comment]
I agree with the proposed changes except for Years. We should add an option to select either the oldest or newest series for grouping.

**Comment by da3dsoul** [comment]
How so? I believe that Years should be strictly by series. If you go to 1986, Macross should be there, but only the first one, not the rest. The same for basically every year since. Although, years is special, because I think a series should show up if it aired in the year, not just started, eg naruto shows up in multiple years. Shippuden shouldn't be in 2002, though, even though naruto should be. When browsing by years, I'm usually looking for a show that will very likely fit the common standards of the time period. If I choose 1986, I don't want a show made in 2014, even if it is a sequel to something that old.

**Comment by ElementalCrisis** [comment]
So the series will show in multiple years? Makes sense, I agree.
