### ISSUE TITLE
Error while trying to delete files From unrecognized

### ISSUE THREAD

**Issue by Blackdixxa** [japanesemediamanager/ShokoServer#511]
I have those errors while trying to delete a file from the unrecognized.

![delete1](https://cloud.githubusercontent.com/assets/10331553/20317675/53cd1376-ab67-11e6-8113-5bdcece38bef.png)
![delete2](https://cloud.githubusercontent.com/assets/10331553/20317674/53cbfb4e-ab67-11e6-9800-0d698512897b.png)

here is a clean log with the error
[2016-11-15.txt](https://github.com/japanesemediamanager/ShokoServer/files/592772/2016-11-15.txt)

**Comment by maxpiva** [comment]
The real error, is access denied. Make sure JMM Server has write access to the network folder.

**Comment by Blackdixxa** [comment]
JMM has write access to the network folder every function works except deleting files

**Comment by maxpiva** [comment]
Extract from your own log:

JMMServiceImplementation.DeleteVideoLocalPlaceAndFile Deleting video local record and file: \\nasf18e02\Download\Drop\[KamiFS]_Dragon_Ball_Super_-_066_[720p_x264]_[10bit]_[505B9308].mkv

JMMServiceImplementation.DeleteVideoLocalPlaceAndFile System.AggregateException: One or more errors occurred. ---> System.UnauthorizedAccessException: Access is denied.

JMMServiceImplementation.DeleteVideoLocalPlaceAndFile Deleting video local record and file: \\nasf18e02\Download\Drop\[KamiFS]_Dragon_Ball_Super_-_066_[720p_x264]_[10bit]_[505B9308].mkv

JMMServiceImplementation.DeleteVideoLocalPlaceAndFile System.AggregateException: One or more errors occurred. ---> System.UnauthorizedAccessException: Access is denied.

There is issues with some people on network shares, please ask in support, how to setup the correct permissions, so JMMServer can have full access.

**Comment by Blackdixxa** [comment]
Cifs are opened for range ip without any password inside my lan the same vm download to the folder and JMM can rename and move file correctly in the right directory on import.
Just delete function cause this error

**Comment by maxpiva** [comment]
Just in case i changed the delete command a little, but i doubt that will fix your problem. Please make sure the User that run JMMServer has Full Access Privileges to the file in question.
