### ISSUE TITLE
Trakt broken in Beta 3.7.0.903

### ISSUE THREAD

**Issue by Blackdixxa** [japanesemediamanager/ShokoServer#512]
Here is the log for trakt it's not synchronizing at all 
[trakt broken.txt](https://github.com/japanesemediamanager/ShokoServer/files/592872/trakt.broken.txt)

**Comment by RickDB** [comment]
Added fix for the error from log however for the underlying cause (missing episode ref) would need a full log with this fix in place, next daily release will have it and in doubt can always ask on discord :)
In the meantime will let Trakt sync a few times to see if I can reproduce it here.

**Comment by miracle152004** [comment]
Hi,

I am still having this issue with the current stable.
Here the logfile from today:

[2017-05-22.txt](https://github.com/japanesemediamanager/ShokoServer/files/1020289/2017-05-22.txt)
