### ISSUE TITLE
When messing around with Import / Watched Folders filelocation is not updated

### ISSUE THREAD

**Issue by kusco123** [japanesemediamanager/ShokoServer#513]
3.7 beta

During my curent issue (Files from Drop Folder are not moved to Drop destination) I started playing around with th settings a little bit. Before I hade
Anime\ as to be watched for new files, Anime\Drop as Drop Source and Anime\_2016 as drop Destination. As I read that "watch for new Files" option will leave them in the Folder and the drop folder was as it's a subfolder of Anime also watched - maybe taht's teh reason (even if it worked for years now). OK - I have changed the path to Anime\Year\_2015, Aniem\Year\_2016 and so on, moved the files and rerun the import (expecting that the Fiel path will be correceted - as it was in the past - but - no. The files are shown with an exclamation mark with the old paths (only a small number are showing the corect one) and - when checking at the Files Tab in JMM Desktop (Collection - Series - Files) the correct path is shown?! And I can open the folder from that view without problems.

When running the Importer it only shows entries like that:
`[2016-11-15 18:40:39:539] Info|BackgroundWorker.OnDoWork => MainWindow.workerImport_DoWork => Importer.RunImport_NewFiles Processing File 3272/22161 --- \\192.168.0.3\Anime\Year\_2013\Strike the Blood\[HorribleSubs] Strike the Blood - 18 [720p].nfo
[2016-11-15 18:40:39:539] Info|BackgroundWorker.OnDoWork => MainWindow.workerImport_DoWork => Importer.RunImport_NewFiles Processing File 3273/22161 --- \\192.168.0.3\Anime\Year\_2013\Strike the Blood\[HorribleSubs] Strike the Blood - 19 [720p].nfo
[2016-11-15 18:40:39:539] Info|BackgroundWorker.OnDoWork => MainWindow.workerImport_DoWork => Importer.RunImport_NewFiles Processing File 3274/22161 --- \\192.168.0.3\Anime\Year\_2013\Strike the Blood\[HorribleSubs] Strike the Blood - 20 [720p].nfo
[2016-11-15 18:40:39:555] Info|BackgroundWorker.OnDoWork => MainWindow.workerImport_DoWork => Importer.RunImport_NewFiles Processing File 3275/22161 --- \\192.168.0.3\Anime\Year\_2013\Strike the Blood\[HorribleSubs] Strike the Blood - 21 [720p].nfo`

**Comment by ElementalCrisis** [comment]
Try running Remove Missing Files and Run Import.

**Comment by kusco123** [comment]
I did ... same result.

Am 27.11.2016 00:38 schrieb "ElementalCrisis" <notifications@github.com>:

**Comment by ElementalCrisis** [comment]
Hmm, are the local paths correct? If Server is on another computer they should reflect the path from your computer to the computer Server is on.

**Comment by kusco123** [comment]
Yes They are. I am Running now a  complete new import (again) to see if it
will work ...

Am 27.11.2016 00:44 schrieb "ElementalCrisis" <notifications@github.com>:

**Comment by kusco123** [comment]
It is no configuration issue for Sure.

Am 27.11.2016 12:44 Vorm. schrieb "ElementalCrisis" <
notifications@github.com>:

**Comment by ElementalCrisis** [comment]
Any ideas @maxpiva?

**Comment by maxpiva** [comment]
I really don't know, can anyone explain me where is the bug? Is the path \\192.168.0.3\Anime\Year\_2013
Correct, Belonging to one of the import folder.

For sure, if you play with the import folders, and there is hash to be made in the queue, some problems may arise, since the command takes the entire filename, if you rename your import folder, the path in the command will be no longer valid.

**Comment by da3dsoul** [comment]
This should be fixed now with the recent changes.

**Comment by hidden4003** [comment]
I added some files, then renamed folder and changed import folder path, then pressed run import, no new files were found. So looks like its fixed.
