### ISSUE TITLE
Multiple Instances

### ISSUE THREAD

**Issue by currowth** [japanesemediamanager/ShokoServer#514]
The new 3.7 beta took out the feature to allow multiple instance. Can you bring back this feature. 
I know that bringing this back will cause issue with the new settings being stored in "%programdata%". 

Can you make it so the server and client lets you choose where you want to store the settings, or lets you choose to keep the settings in current working directory. This would be a useful feature that would make this program portable.

**Comment by da3dsoul** [comment]
Not a bad idea, but it wasn't designed to be portable. It's a server->client software. The server doesn't move and can be accessed by clients anywhere.

**Comment by bigretromike** [comment]
I just would like to know ```WHY``` you want multiply instance ? 
You want to support few users simultaneous ? Maybe you need this one more #426 ?

**Comment by maxpiva** [comment]
Already supported with the instance {name} as arguments in the command
line, you will need an extra settings.json inside the instance name
directory inside C:\programdata\

**Comment by currowth** [comment]
I want multiple instances because currently there is only one drop folder.

**Comment by currowth** [comment]
@maxpiva I tried your suggestion, and it worked like a charm. Thanks for your help.

**Comment by da3dsoul** [comment]
You'll like #504

**Comment by bigretromike** [comment]
So it was all about multiply drop folders 👍
