### ISSUE TITLE
better handling of ban timers

### ISSUE THREAD

**Issue by CuddleBear92** [japanesemediamanager/ShokoServer#521]
i think the ban system is a bit messed up ATM. 
while things should be alot smoother now, its still not perfect.
http bans are happening over udp bans now. 

one thing i think would help is if the banned message on the server and desktop didnt not get removed. and that we got a dropdown menu on that same line that the user can choose timers on.
say 1, 2, 6, 12, 24, 48 hours choices kinda like how we have update rates on metadata. 

this way we can force the system to wait as long as we want without turning the server off all the way.

**Comment by ElementalCrisis** [comment]
Leaving this in the user's control is probably not the best idea, could lead to abuse and a permanent ban. We can look at adding something internally to our current system, any ideas @hidden4003?

**Comment by hidden4003** [comment]
Made a hotfix

**Comment by bigretromike** [comment]
This looked like fixed issue. @hidden4003 added lock and `if`s so we should be fine.
