### ISSUE TITLE
fatal error, server stopped responding under anidb refresh

### ISSUE THREAD

**Issue by AreFinstad** [japanesemediamanager/ShokoServer#523]
fatal error, server stopped responding under anidb refresh.
Server Version 3.7.0.904
unsure why. here is a cutout of the log:

[2016-11-29 05:21:09:638] Fatal|Path.GetPathRoot => Path.LegacyNormalizePath => UnhandledExceptionManager.GenericExceptionHandler Date and Time:         29/11/2016 05:21:09
Machine Name:          ARE
IP Address:            198.18.1.114
Current User:          ARE\Are

Application Domain:    ShokoServer.exe
Assembly Codebase:     file:///D:/Programs/Shoko/Shoko Server/ShokoServer.exe
Assembly Full Name:    ShokoServer, Version=3.7.0.904, Culture=neutral, PublicKeyToken=null
Assembly Version:      3.7.0.904
Assembly Build Date:   12/11/2016 18:43:50

Exception Source:      mscorlib
Exception Type:        System.IO.PathTooLongException
Exception Message:     
Exception Target Site: LegacyNormalizePath

---- Stack Trace ----
   System.IO.Path.LegacyNormalizePath(path As String, fullCheck As Boolean, maxPathLength As Int32, expandShortPaths As Boolean)
       ShokoServer.exe: N 13815764
   System.IO.Path.GetPathRoot(path As String)
       ShokoServer.exe: N 00048
   System.IO.RenamedEventArgs.get_OldFullPath()
       ShokoServer.exe: N 00060
   JMMServer.AdvFileSystemWatcher.OnRenamed(sender As Object, e As RenamedEventArgs)
       AdvFileSystemWatcher.cs: line 0171, col 13, IL 0000
   System.IO.FileSystemWatcher.OnRenamed(e As RenamedEventArgs)
       ShokoServer.exe: N 00183
   System.IO.FileSystemWatcher.CompletionStatusChanged(errorCode As UInt32, numBytes As UInt32, overlappedPointer As NativeOverlapped*)
       ShokoServer.exe: N 00617
   System.Threading._IOCompletionCallback.PerformIOCompletionCallback(errorCode As UInt32, numBytes As UInt32, pOVERLAP As NativeOverlapped*)
       ShokoServer.exe: N 00125

here is the logs itself for that day. crashed at the very end ofc :D 
https://puu.sh/sxZma/0d32072b81.zip

Note, just making this issue to make sure its nothing wrong with release :D

**Comment by maxpiva** [comment]
Seems to a path problem, seems you have a path too long, on one of watched folders. Nothing we can do about it...
