### ISSUE TITLE
Renamer intermittently removes extension

### ISSUE THREAD

**Issue by Cazzar** [japanesemediamanager/ShokoServer#529]
On occasion the Renamer can also remove extensions on the file, a couple of examples, I have of this are filenames such as: 
>./To Love-Ru Trouble - Darkness 2nd/To Loveru- Darkness 2 - 14 (1280x720 Blu-ray H264) [78809E30]
>./To Love-Ru Trouble - Darkness OAD/To Love-Ru- Trouble - Darkness OAD - 08 (1024x576 %vid 10bit) [30F28B96]

The renamer format I am using in the

```IF G(!) DO ADD '[%grp] '
IF I(eng) DO ADD '%eng '
IF I(ann);I(!eng) DO ADD '%ann '
IF T(!Movie) DO ADD '- %enr'
IF F(!1) DO ADD 'v%ver'
DO ADD ' (%res'
IF R(DVD),R(Blu-ray) DO ADD ' %src'
DO ADD ' %vid'
IF Z(10) DO ADD ' %bitbit'
DO ADD ') '
DO ADD '[%CRC]'
DO REPLACE 'H264/AVC' 'H264'
DO REPLACE '0x0' ''
DO REPLACE '__' '_'
DO REPLACE '__' '_'
DO REPLACE '<' '('
DO REPLACE '>' ')'
DO REPLACE ':' '-'
DO REPLACE '"' '`'
DO REPLACE '/' '_'
DO REPLACE '/' '_'
DO REPLACE '\' '_'
DO REPLACE '|' '_'
DO REPLACE '?' '_'
DO REPLACE '*' '_'
```

Log files for the relevant day that these files were renamed:
It should be early for the files to be renamed, as it was done 1:30AM-2AM
[2016-12-09.zip](https://github.com/japanesemediamanager/ShokoServer/files/651009/2016-12-09.zip)

**Comment by da3dsoul** [comment]
[2016-12-09.txt](https://github.com/japanesemediamanager/ShokoServer/files/651859/2016-12-09.txt)
Smaller version with trash cut out

**Comment by da3dsoul** [comment]
We should move the renaming to use VideoLocal_Places. You can have the same file in two places now, and they don't need to have the same name.

**Comment by da3dsoul** [comment]
Hopefully this is fixed now.

**Comment by Cazzar** [comment]
bcce5b943afd00baa43cdaf169fa04bfbe7a0299
