### ISSUE TITLE
invalid duplicate files

### ISSUE THREAD

**Issue by bond4u** [japanesemediamanager/ShokoServer#534]
they show up in "duplicates", but full path matches.
JMM Desktop and Server 3.6.1.0.
![image](https://cloud.githubusercontent.com/assets/66413/21483187/e48fc720-cb86-11e6-98d8-69d9eb0316cd.png)

**Comment by da3dsoul** [comment]
In latest dailies, remove missing files has a clean up function to fix that.

**Comment by bond4u** [comment]
Nevermind, after another "re-evalute" they disappeared.

**Comment by da3dsoul** [comment]
Cool go ahead and close this then
