### ISSUE TITLE
multiple db entries linking to same file

### ISSUE THREAD

**Issue by bond4u** [japanesemediamanager/ShokoServer#535]
I have file renaming, but it's failing sometimes.
1.Is there a way to avoid creating multiple database entries which link to same file? Check before overwriting a file?
2.Where does CRC come from? Anidb? Can it be calculated locally when missing?
JMM Desktop and Server 3.6.1.0
![image](https://cloud.githubusercontent.com/assets/66413/21483627/0c4e228c-cb8e-11e6-9dae-0431655c0624.png)

**Comment by da3dsoul** [comment]
CRC is calculated with the hasher. I don't remember if I made some of the new cleanup stuff fix that. I'll check and make it just in case.

**Comment by da3dsoul** [comment]
Remove Missing Files now also cleans up duplicates.

**Comment by da3dsoul** [comment]
I would recommend editing you rename script to only add [%crc] if it is available.

**Comment by bond4u** [comment]
so, if there is a file then there is also a crc?
in unrecognized view, some files are missing a crc...
![image](https://cloud.githubusercontent.com/assets/66413/21741716/684b43a0-d4e7-11e6-8790-3e3f62e2cc68.png)

**Comment by da3dsoul** [comment]
You can rehash those if you want.

**Comment by da3dsoul** [comment]
It should fill the CRC

**Comment by da3dsoul** [comment]
You should be able to sort by it as well and shift click

**Comment by bond4u** [comment]
Yeah, after "rehash all" they were gone.
But after server restart and a day or two later they were back or there were new ones - I'm not sure.

**Comment by da3dsoul** [comment]
Hmm. That's likely a different issue. Hashing is slow now, so it'll be something to look at when we look at optimization.
