### ISSUE TITLE
Installation of .NET Framework 4.6.1 fails within installer

### ISSUE THREAD

**Issue by Terr4** [japanesemediamanager/ShokoServer#540]
I just freshly installed my server and during the installation of Shoko Server I got an information message about the .NET Framework 4.6.1. I could only click OK and Shoko Server was installed apparently successfully. However on startup it always crashed.

The issue is that the installation of the Framework is apparently wrongly implemented in the installer. Please see the screenshot of the message.

I then deinstalled Shoko Server and also deleted the Program Data files manually. Then installed the .NET Framework manually and then Shoko Server again to fix this issue.

![bildschirmfoto 2016-12-29 um 13 25 31](https://cloud.githubusercontent.com/assets/6331473/21603387/2eb0bee2-d19d-11e6-812c-bebd10a68a91.png)

**Comment by RickDB** [comment]
@ElementalCrisis looks we have a missing switch for .NET installer inNSISjudging by the error :)

**Comment by ElementalCrisis** [comment]
Hmm, I've changed the commands and it seems to work for me. Will see if I can get someone to test.

**Comment by RickDB** [comment]
Confirmed fixed during test here 👍

**Comment by Terr4** [comment]
thx! :)
FYI It was on Windows Server 2008 R2

**Comment by ElementalCrisis** [comment]
I'm going to close this, not sure if you'll be able to but when the new version is out can you try installing again and see if it installs?
