### ISSUE TITLE
Can't open an issue in Shoko Desktop

### ISSUE THREAD

**Issue by yhoogi** [japanesemediamanager/ShokoServer#543]
.. as there is no button for that.

**Comment by ElementalCrisis** [comment]
ShokoDesktop is our WIP for the new client. 
https://github.com/japanesemediamanager/ShokoDesktop

ShokoClient is the existing client.
https://github.com/japanesemediamanager/ShokoClient

**Comment by yhoogi** [comment]
The Shoko Client is called Shoko Desktop in my installation
Therefore the confusion

![grafik](https://cloud.githubusercontent.com/assets/10504005/21655054/932e5f52-d2b8-11e6-9383-c6a6480db1e5.png)

**Comment by ElementalCrisis** [comment]
Yeah it's a fun game of the GitHub repo being called client while the program is called Desktop. :)
