### ISSUE TITLE
Option to delete lower quality releases on import of new release

### ISSUE THREAD

**Issue by da3dsoul** [japanesemediamanager/ShokoServer#545]
The definition of better release is as follows.

BD>DVD>HDTV>TV>www>unknown
Resolution is obvious
Chaptered over not chaptered
Take more audio streams over quality and resolution
Higher version of same release trumps

Possibly allow the above to be customizable.

This happens after drop folder location resolution, but before drop folders move (free space), and before renaming.

I'll do the back end unless someone else beats me to it. I'd like help with the UI if we make it customizable.

**Comment by bond4u** [comment]
Bitrate.
Hard to tell what's optimal.
Higher resolution, but low bitrate is sometimes worse than lower resolution.
And some personal preferences: for me FLAC is waste of space and I'm not going higher than 720p

**Comment by Cazzar** [comment]
The thing is, quality is really subjective, it's hard to really determine
what is best, and a blanket solution is kinda impossible.

**Comment by da3dsoul** [comment]
For now, I'm doing a sub group preference list. That trumps resolution and bitrate. The current version just does highest resolution and most lossless audio codecs. It'll be more configurable one I get more base code down and get more feedback.

As for feedback, I'm thinking a solution to the import deletion problem is having a configurable list of checks a file must meet in order to be kept. These checks may be a minimum source quality (BD), minimum resolution, etc.

**Comment by da3dsoul** [comment]
There will be exceptions as well, such as v2 files, which will always delete the v1

**Comment by ElementalCrisis** [comment]
Since this is being added as an extension of the multiple files utility, will there be an option to have it run automaticlly once a week or so?

**Comment by da3dsoul** [comment]
No, it'll be on import and manually. No point in running it all the time if nothing has changed.

**Comment by bond4u** [comment]
On 2nd thought - most stuff these days is probably variable bitrate.

**Comment by da3dsoul** [comment]
That too

**Comment by da3dsoul** [comment]
This is coming along nicely. Almost all of the back-end work done!

**Comment by da3dsoul** [comment]
TODO: Make File Summary in all tabs follow this. Add Dual Audio, Multi Audio, and Multi Sub Icons.

**Comment by da3dsoul** [comment]
Closed! Will need more testing, but it is done!

**Comment by da3dsoul** [comment]
I got a reply from anidb regarding chapters. There may be older files with chapters that are listed as not having them, but what do have it available if we are willing to assume it's not going to always be correct. Noting for myself. bit & 4096

**Comment by da3dsoul** [comment]
Chapters vs no chapters will be nice

**Comment by bigretromike** [comment]
thank you ! I needed this so much
