### ISSUE TITLE
Version update information inconsistent

### ISSUE THREAD

**Issue by t0815** [japanesemediamanager/ShokoServer#547]
hi there,

there seems to be an inconsistency with available version (updates) for ShokoServer.

![image](https://cloud.githubusercontent.com/assets/10379828/21898480/4b0109b0-d8ed-11e6-8b98-9bfab4406ce5.png)

Same goes for ShokoDesktop, but ill post it here regardless to avoid duplicates.

![image](https://cloud.githubusercontent.com/assets/10379828/21898560/7e231cca-d8ed-11e6-8d8b-5349679da577.png)

**Comment by ElementalCrisis** [comment]
For Server you seem to be on the Beta update channel, change the channel in the About window and restart server.

For Desktop, that is the correct reported version, I forgot to update the file it's checking against.

**Comment by t0815** [comment]
ah, it does not change as you click the combobox  :) . Now i get the 3.7.0.1 there too. Ok, can be closed then i guess.
