### ISSUE TITLE
migrate migration failed stack trace from out of the window title

### ISSUE THREAD

**Issue by Scrxtchy** [japanesemediamanager/ShokoServer#548]
![](https://upload.teknik.io/G2yoN.png)

**Comment by ElementalCrisis** [comment]
What version are you running? 

Try initially running as an Admin so it can create the folders in programdata.

**Comment by Scrxtchy** [comment]
Running 3.7.0.904
I have been running the application as the administrator user on my server, but only had select files available for a jailed user to access, since they were created by the administrator user.
Rewrote NTFS permissions for the ShokoServer folder in program data for \Users to fix the underlying issue

But only was able to know the issue by copying the dialogue menu's contents, as the title and detail fields are flipped
https://github.com/japanesemediamanager/ShokoServer/blob/ff7b11769602e88f1d3e6f124f3368299e17bd56/JMMServer/ServerSettings.cs#L400

Should be {text} {caption}
https://msdn.microsoft.com/en-us/library/ms598679(v=vs.110).aspx

**Comment by ElementalCrisis** [comment]
You're running the beta still, update to the latest stable as it should fix your problems.

http://jmediamanager.org/downloads/
http://jmediamanager.org/changelog/

**Comment by Scrxtchy** [comment]
Interesting, Thought I updated this last it was online, thanks for the heads up
