### ISSUE TITLE
SQLite error, if server is killed while creating the database

### ISSUE THREAD

**Issue by Tomelyr** [japanesemediamanager/ShokoServer#558]
Error is pretty much straight forward. If you kill the server, while it's creating the database, the database is corrupted and the patchCommands is spitting errors, since the tables arent created.

It can happen while normal use, if you swap the language.

Steps to reproduce:

1. Clean install of ShokoServer
2. Start ShokoServer
3. Swap Language
4. Accept the box, which states that you need to restart the server to swap the language.

and now everytime you start, patchCommands will error, due to the time it takes for the first time to create the database and still encouraging the user to restart.

Log file:
[2017-01-24.txt](https://github.com/japanesemediamanager/ShokoServer/files/726334/2017-01-24.txt)

**Comment by bigretromike** [comment]
This should help with this problem.
