### ISSUE TITLE
Support linked ed/op that are not stand alone episode (in anidb)

### ISSUE THREAD

**Issue by bigretromike** [japanesemediamanager/ShokoServer#563]
## PLEASE READ BEFORE POSTING YOUR ISSUE

Please create GitHub issues only for bugs and feature requests. If you need help with using Shoko or have a question, join us on Discord.
https://discord.gg/vpeHDsg

===== Guidelines ====

- Make sure you are using the latest version of Shoko Server otherwise your issue will be closed.
- Search this repository (top of the page) for the issue or feature you are reporting, make sure it has not been fixed or reported before.
- If reporting an issue, then you must attach the relevant Shoko Server LOG FILE. 
- If requesting a new feature, please explain in detail the feature itself and the benefits of it being added.
- If requesting cosmetic changes, please explain in detail why they should be made. 
- The template below MUST BE USED when submitting an issue, no exceptions. -->

## LOG FILE

ATTACH YOUR LOGS HERE

## Description

When adding serie that use linked chapters (ex. mkv) there are op/ed extracted from them and linked. Those files tend to be not included in db sources as ep/op as they are part of episodes. also without moving them (with original name) to same location as episode they are left alone and episodes are without part of them. If we could link them to series (manualy?) but add them to "offline episode" or something that wouldn't be in db source but still make file to travel along with series so at the end we dont lose that op/ep while moving/renaming. 

Ex. adding Single Episode : ex. Not linked - that would virtualy link file into serie and move it and be saved in cache but wont be sync (as its virtual) to 3rd party source db's

## STEPS TO REPRODUCE

Being as detailed as possible, please list all steps need to reproduce the issue, if we can't reproduce it then we can't fix it.

**Comment by da3dsoul** [comment]
Just add it to anidb, it's supported and encouraged. It's way too much work to start making fake records outside the scope of anidb. Like major internal changes that will take months to iron out.

Yeah.... Just add to anidb and save everyone else the effort of trying to manual link.

**Comment by bigretromike** [comment]
yet still. renaming this linked chapter will result in breaking it..

**Comment by da3dsoul** [comment]
You don't need to. AVDump it like any other and label it as OP2 or whatever

**Comment by da3dsoul** [comment]
You need to actually go to anidb and click add episode though

**Comment by bigretromike** [comment]
i know. but renaming it will break chapter-linked-playback;
Im asking for feature that would prevent it from that or store orginal name...

**Comment by da3dsoul** [comment]
If you have a rename script, then just tell it not to rename if it's an OP or ED

**Comment by bigretromike** [comment]
as you wish; i will think when anidb start to reject those

**Comment by da3dsoul** [comment]
Yeah, it'd be nice if you could change the chapter info and have it still be recognized, but that's a long shot
