### ISSUE TITLE
File is treated as Duplicate even when there is only one file (also duplicate row info is duplicated)

### ISSUE THREAD

**Issue by bigretromike** [japanesemediamanager/ShokoServer#577]
## Description

I'm having in Shoko Desktop in "Duplicate Files" duplicated files that point to same file.
Basically I have two same entries;  
I cannot delete one of them via Desktop because I will end up deleting the only file I have;

If there is no way to make a proper duplicate searcher then could there be a 'delete' but without removing file ? because now If I click "No" if I want to delete file it act as cancel and close dialog without doing anything.

Also this is not UNIX path problem as the both files path are the same 1:1

Also the same is for Duplicate rows. I sometimes have them duplicated;

**Comment by bigretromike** [comment]
This could happen because of multiply move, source/dest folders and reimporting/rescaning;
Cant tell for sure as I do it not as often as I would like to;
Some check for path (without lowering) could be helpful;

**Comment by da3dsoul** [comment]
Run remove missing files, then got revaluate in the duplicate section

**Comment by bigretromike** [comment]
Running Re-evaluate all entries don't help;
(is it server re-evaluating or client)(or other way does client have to have access to files?)

**Comment by da3dsoul** [comment]
Those are in order. Run remove missing files first, then reevaluate when it's finished. It reevaluates on the server

**Comment by bigretromike** [comment]
that didn't removed files that are duplicate but is not; 
1. missing files - file is there so both rows are left there <- also this remove file from MyList (sic! - shouldn't this leave files as those could be on removable drivers ? )
2. reevaluate - both rows stayed;

For double rows I just double pick the same file to delete so it wouldn't delete both;

For row that contain same file, this didn't helped;

**Comment by bigretromike** [comment]
Nevemmind. I deleted them manualy
