### ISSUE TITLE
Shoko is crashing during import do to a damage file

### ISSUE THREAD

**Issue by shadowkamui** [japanesemediamanager/ShokoServer#583]
## LOG FILE
[2017-02-17.zip](https://github.com/japanesemediamanager/ShokoServer/files/785993/2017-02-17.zip)

## Description

OK looks like shoko is crashing on import when he find a damage file and after that when you try to restarted and he start cashing up he crash again. This crash dos not appear in the shoko logs but in the windows log and marked as a Faulting module path: C:\WINDOWS\SYSTEM32\ntdll.dll.

I try to import to with JMM because I dint have a problem with that and I had this problem when updating to shoko. JMM do crash the same as shoko during the import but after you restarted he do the caching up and continue the proses don’t know if he ignore the file or what.

I know that the problem is a file because when I remove the folder whit the file and open shoko again he continue the import process without a problem.

I am using the shoko server in mi main pc and I was importing a folder that is network drive from mi nas|

**Comment by maxpiva** [comment]
This probably triggers an unhandled exception, we probably cannot do anything about this, , until we have more information about, exact log information, stack error info there is no way for us to pinpoint the failure. So i'm closing this, feel free it to open, if more information of how to pinpoint the failure, or where.
Windows OS is not good with damage files.
