### ISSUE TITLE
Questions about ApiV2

### ISSUE THREAD

**Issue by Rand-Random** [japanesemediamanager/ShokoServer#585]
@bigretromike 

Hi.

I am in the process of implementing the annotation system @maxpiva did in the ApiV2.

I have some basic questions about the ApiV2:

1. Why is there a Counter (https://github.com/japanesemediamanager/ShokoServer/blob/master/Shoko.Server/API/v2/Models/core/Counter.cs) class that basically just have an int member? why dont the methods return the int directly?
2. Why are some methods marked as Post and return ApiStatus/ApiMessage where others that also only return ApiStatus/ApiMessage are marked as Get? you could compare the /folder/edit => EditFolder with /folder/import => RunImport
3. Why do we have duplicate logic checks? You can look at https://github.com/japanesemediamanager/ShokoServer/blob/master/Shoko.Server/API/v2/Modules/Common.cs#L193 and https://github.com/japanesemediamanager/ShokoServer/blob/master/Shoko.Server/API/v1/Implementations/ShokoServiceImplementation.cs#L3092 is it save for me to remove the duplicate conditions in ApiV2?

I am just starting the work and there may be more questions poping up the longer I work on this one

**Comment by da3dsoul** [comment]
Because it's a major clean up. Most of that was copy paste. Also @japanesemediamanager/API is a thing

**Comment by bigretromike** [comment]
Thank you for poinitng out code. As for counter, nancy handle thing via models and later the counter can be modyfy without breaking backcompatible. Second some methods are post when you input/create data with them or are in middle of clean up as folder/ was way before ParameterAPI exists. Third, you pointing to v1 (legacy) code. As da3dsoul point out it was mostly copy-pasted and edited to work so we could have old client working while cuting out non nancy implementation. Also jmm code tend to be edited by many and sometimes validation of variables are cut out, its better to chcek it twice than 0 times. Also some of old code dont respond with bools when there is a null object. Thats is in general the case. But in this given case (as its apiv1) its a copy-paste thing.

**Comment by bigretromike** [comment]
This has been answered and there were no additional questions. If there are please reopen it.
