### ISSUE TITLE
"Update All TvDB Info" not working

### ISSUE THREAD

**Issue by Baine** [japanesemediamanager/ShokoServer#587]
## LOG FILE

full:
[2017-02-27.txt](https://github.com/japanesemediamanager/ShokoServer/files/802685/2017-02-27.txt)

## Description

Shoko Server complains that it can't add duplicate entries to dbo.TvDB_Series

## STEPS TO REPRODUCE

ShokoServer compiled from master cb785f2676decbab7b9096d5451700e62185c1cd
Launch Shoko Server, connect to mssql server, wait for initialization
Tab Actions --> hit "Update all TvDB Info" --> check log

**Comment by da3dsoul** [comment]
Check this. I think it is fixed now.

**Comment by Baine** [comment]
yep, is fixed :)
