### ISSUE TITLE
HTTP bans on refactor

### ISSUE THREAD

**Issue by CtrlAltDefeat94** [japanesemediamanager/ShokoServer#588]
Commit; 0aacabf943f6e02024777b16c9f373bb02894e10

I seem to still be running into HTTP bans on refactor. 
Below is a log from the point of booting Shoko, until the point of the ban.

For this test I had an empty DB that I let Shoko Server identify some random files from, to then lookup show/episode/etc information. *Some* files had been already imported when this log starts.

LOG:
https://gist.github.com/CtrlAltDefeat94/8207904532524e53ca2bc57a640c540a
Note, please ignore the H rated results, this is a dummy db for the purpose of getting the HTTP ban, given that my own queue is empty/not doing much per day

**Comment by hidden4003** [comment]
After filtering your log I do not see any requests that are exceeding the limit rate, please make sure you don't have some other software like Plex or your main server (you mentioned this one was for testing) didn't query anidb at the same time.

From the log provided I see no issues with the limiter.

**Comment by hidden4003** [comment]
What I think happened is the anti-leech protection kicked in as you requested a lot of items sequentially which is somewhat unnatural behavior I guess. I remember anidb mods mentioning they have something of the sort.

**Comment by CtrlAltDefeat94** [comment]
I am 100% certain that there was nothing else calling AniDB at the time of this testing.
The calls being sequential could be a very valid reason. I've had bans before for this reason when I did API things myself...
The fact that they are sequentially here is because I did not randomize file info that I put in the DB(I 'hacked' files I do not have into this DB for the sake of having a queue to run)

I've experienced bans on my own DB which did not have this order, so I've made a dummy db with a randomized order this time to try again and see if I'll get banned

**Comment by hidden4003** [comment]
Closing for now, feel free to reopen.

**Comment by CtrlAltDefeat94** [comment]
I've been running nearly nonstop for the past few days and I haven't gotten a single ban \o/

**Comment by Remnence** [comment]
@CtrlAltDefeat94 Is there an easy way I can do this to my current DB? I've been getting banned almost daily.

**Comment by da3dsoul** [comment]
By 'do this', what do you mean? If you mean upgrade to the latest commit, you can, but I wouldn't recommend it unless you are familiar with SQL, and be are prepared for desktop to be half working at best.

**Comment by Remnence** [comment]
@da3dsoul I was thinking it was query or something he had developed to randomize the data in the tables. My current DB is fairly large and I experience bans almost daily. I'm decent with SQL but I haven't looked at the structure of Shoko enough to mess around on my own.

**Comment by da3dsoul** [comment]
Well that's fine. We can help by telling you where things are, or how they are used, but teaching someone how to set up DB managers, test data with queries, etc is annoying. 

No refactor just has a few fixes that have been nice and stable for bans.

**Comment by CtrlAltDefeat94** [comment]
@Remnence I added(or hacked really) files in a random order into my dummy database for testing purposes. Not sure how it could be done with an existing queue though
