### ISSUE TITLE
Faulty or incomplete links being pulled from webcache

### ISSUE THREAD

**Issue by CtrlAltDefeat94** [japanesemediamanager/ShokoServer#594]
## Log
[server.txt](https://github.com/japanesemediamanager/ShokoServer/files/873590/server.txt)
[desktop.txt](https://github.com/japanesemediamanager/ShokoServer/files/873589/desktop.txt)

## Description

Some shows fail to be linked correctly using webcache. I tried mapping Pocket Monsters Advanced Generation and the first time it only mapped TvDB show Pokémon Season 6 to episode 1(which is correct) and the 2nd time I tried, mapping went completely haywire, like this;
![image](https://cloud.githubusercontent.com/assets/5640470/24375024/2c2b44ea-1337-11e7-86cb-28c25fcc413c.png)
NOTE! not all links displayed in this image were done around the time the log ends, as apparently it added even more stuff(of which -some- are correct)

## STEPS TO REPRODUCE
- Add Pocket Monsters Advanced Generation(AniDB ID 1041) (I can deliver files if need be)
- Whichever required steps to use webcache for TvDB(None I think?)
- Try adding webcache suggestions;
- See only Season 6 gets mapped to episode 1 (which is correct, but there are more links on Webcache)
- Try to add webcache suggestions again _without removing the previously made one_
- See result in screenshot

**Comment by CtrlAltDefeat94** [comment]
@da3dsoul

**Comment by CtrlAltDefeat94** [comment]
Just noticed similar if not the same happening to Trakt.
I'll try to grab some log of that in the morning

**Comment by da3dsoul** [comment]
Trakt is negligible. It'll be fixed when TvDB is. For reference, is this on latest master?

**Comment by CtrlAltDefeat94** [comment]
Server 3.7.0.6 yes

**Comment by da3dsoul** [comment]
That's not master, but you answered my question

**Comment by CtrlAltDefeat94** [comment]
Whoops, I'm getting too used to master containing the latest official release

I can try it on daily if you want?

**Comment by da3dsoul** [comment]
Yes please

**Comment by CtrlAltDefeat94** [comment]
Tested on 39a68435264c9a2f15c851d77fd306843ef5c54e
It takes forever to populate, but I haven't had any flacky links yet

**Comment by da3dsoul** [comment]
Hmm I'll need to figure out what takes so long. Are you using sqlite?

**Comment by CtrlAltDefeat94** [comment]
Mysql, I can take a better look if you like, but I'm betting it's because _a_ capper on the API calls that are being done. For AniDB that's quite logical because we all know what happens if we don't, but I'm not sure why TvDB would be capped so strict

**Comment by da3dsoul** [comment]
I'm looking into it because I don't seem to experience it. What is it that takes forever? I want an action, not a function.

**Comment by CtrlAltDefeat94** [comment]
When I press the "Use This" button for using the Community Recommendation, it takes forever to add all of the links.
[2017-03-31.txt](https://github.com/japanesemediamanager/ShokoServer/files/885514/2017-03-31.txt)

**Comment by da3dsoul** [comment]
Post that on Refactor errors on desktop please

**Comment by da3dsoul** [comment]
Removing a link takes forever as will

**Comment by da3dsoul** [comment]
For future reference: [DotTrace Perf Export](https://www.dropbox.com/s/op99mf3r9vvlfxn/TvDB%20DotTrace%20Perf.rar?raw=1)

**Comment by CtrlAltDefeat94** [comment]
Added both

**Comment by da3dsoul** [comment]
Nope this is a separate issue. I'm going to edit your comment on the other one. I said post it because it has refactor errors, but they aren't directly related to this.

**Comment by da3dsoul** [comment]
I just rewrote most of TvDBEpisode_Repository. Will run a perf test and see how much faster it is now.

**Comment by da3dsoul** [comment]
Left: Before - Right: After
![image](https://cloud.githubusercontent.com/assets/5205810/24555752/391745e8-1600-11e7-8578-c377e4bb58a8.png)

**Comment by da3dsoul** [comment]
Yeah... Big Difference

**Comment by da3dsoul** [comment]
See #595
Getting characters takes 2 whole seconds. This needs to be cut, and the best way is a db refactor of those tables.
![image](https://cloud.githubusercontent.com/assets/5205810/24559509/f407643a-160c-11e7-98da-f8ac23aa1d11.png)

**Comment by CtrlAltDefeat94** [comment]
Just a bit, heh

**Comment by CtrlAltDefeat94** [comment]
Well, TvDB isn't the only one there(MAL needs one too).

Wasn't someone drawing a new DB layout a little while back in the dev channel?

**Comment by da3dsoul** [comment]
When linking or removing a link. Generating the character contracts (which is just a huge join across 5 tables) takes 27% of the whole operation, and it's something that doesn't even need to be done here.

**Comment by maxpiva** [comment]
Let me sit on it 👍

**Comment by da3dsoul** [comment]
@ctrlaltdefeat94 cazzar was drawing a the current DB outline to aid in redesigning it, but I don't think he ever started redesigning the parts that need it.

**Comment by Cazzar** [comment]
For that database diagram, this is the last image I can find of it:

![](https://cdn.discordapp.com/attachments/102170710465585152/277699858318622720/unknown.png)
