### ISSUE TITLE
ED2K Search & Crash with AzureWebAPI Hammering

### ISSUE THREAD

**Issue by kakure** [japanesemediamanager/ShokoServer#597]
## LOG FILE

[2017-04-07.zip](https://github.com/japanesemediamanager/ShokoServer/files/907055/2017-04-07.zip)
[Windows Appilcation Event Log.txt](https://github.com/japanesemediamanager/ShokoServer/files/907057/Windows.Appilcation.Event.Log.txt)

## Description
I started with a clean install of Shoko Server 3.7.0.6, an entirely new SQL Server database, and all fresh settings.  Shoko Server appears to be repeatedly hammering the AzureWebAPI for the same ED2K file over and over again.  After an amount of time, the application crashes with the attached Windows Application Event log.

![shoko server console](https://cloud.githubusercontent.com/assets/27033914/24822989/eaa4e046-1bc7-11e7-8867-992c17994073.png)

The console status, marked in red above, does not change and hangs until the application crashes.  Meanwhile the Shoko Server logs shows hundreds of repeated entries of it trying to access the AzureWebAPI for the same ED2K.

## STEPS TO REPRODUCE
I'm not sure how to specifically reproduce this in another environment, other than trying to submit the ED2K in the same manner to the AzureWebAPI to see what happens.

The steps I take, are:
1. Start Shoko Server
2. Watch it initialize
3. Watch the "Getting file info" not change
4. See the hammering of the AzureWebAPI in Shoko's logs
5. Then, after an amount of time, Shoko Server crashes.  The crash is not logged within Shoko's logs, but within Windows Application Event logs.

I should note, The file it is searching for has the following details, and has been tested good with no strange states to prevent it from being interacted with.
ED2K: F988E2B6D2F0A6C62E7773E5C93879BC
Filename: "Those Who Hunt Elves I - Ep 04[a4e].ogm"

Lastly, I'm not running anything else that ties into Shoko Server (e.g. Shoko Desktop, or any other plugins, etc.).

**Comment by da3dsoul** [comment]
I've noticed this a little, but it's never forever and server breaking. I'll look at it and see if I can find an issue. I do have that exact file scanned correctly.

**Comment by kakure** [comment]
Something I just noticed after starting Shoko Server up after it crashes:
The "Getting file info from UDP API: #" increments +1, then stops (attached below in red).  Even though that number increment +1, the application is still hammering the AzureWebAPI with the same ED2K value.  It does all this until it crashes again.

![shoko server console 38195](https://cloud.githubusercontent.com/assets/27033914/24829501/f24388a6-1c40-11e7-9dee-809fc0ad27a0.png)

Start the application again, and the number increments +1, searches for the same ED2K repeatedly, then crashes again after an amount of time.  

I've attached new logs for the day after starting it up again.
[2017-04-08.zip](https://github.com/japanesemediamanager/ShokoServer/files/907485/2017-04-08.zip)

**Comment by kakure** [comment]
I'm going to install Visual Studio 2017 on my file server to see if I can gleam any facts out of the Just In Time debugging options when Shoko Server crashes.  I'll post the results here, if any, when I'm done.

**Comment by da3dsoul** [comment]
Don't bother, in already fixing it

**Comment by da3dsoul** [comment]
I added a timeout
