### ISSUE TITLE
slow queries

### ISSUE THREAD

**Issue by bond4u** [japanesemediamanager/ShokoServer#606]
So, I just discovered slow.log in mysql data folder.
I ran couple of latest ones with explain and yes there are some subqueries which are not using indexes.

So far I've created 4 indexes:
create index idx_videolocal_hash on jmm.videolocal (hash);
create index idx_xref_epis on jmm.crossref_file_episode (episodeid);
create index idx_xref_subt_file on jmm.crossref_subtitles_anidb_file (fileid);
create index idx_xref_audio_file on jmm.crossref_languages_anidb_file (fileid);

It "feels" faster now, but I don't know if these indexes really are helping.

[slow.txt](https://github.com/japanesemediamanager/ShokoServer/files/924419/slow.txt)

**Comment by bigretromike** [comment]
Index for hash index was present v55;
Other 3 have been added.
