### ISSUE TITLE
Hashing new folder with known duplicate files takes a long time

### ISSUE THREAD

**Issue by Kezxo** [japanesemediamanager/ShokoServer#616]
CC: @maxpiva 
## LOG FILE

https://www.dropbox.com/sh/mcyp1gevc6y6v29/AAD-p9h21fG7ps0wI07cXznLa?dl=0

## Description

I wanted to scan some files and make sure they all got added correctly so I made a new folder and copied the files to it and added it to shoko server as a watched folder. Scanning these files takes a while, I expected it to go real fast since most of the files where known to shoko but it takes 1-2 min to start hashing the next file. 

![shokoserver_2017-05-08_04-00-53](https://cloud.githubusercontent.com/assets/4523551/25788016/58d104d2-33a6-11e7-86d8-45c25a49d89d.png)

## STEPS TO REPRODUCE
- Make a new folder on a local drive
- Copy in some files shoko knows about into it.
- Add the folder to shoko as a watched folder.
- Click "Run Import"

It should now hash these files with a large delay between them

### Alternate shorter steps:

- Copy some known files from one watched folder to another, also on local drives.

**Comment by da3dsoul** [comment]
That explains a lot. Thanks

**Comment by da3dsoul** [comment]
Fixed
