### ISSUE TITLE
Nancy POST API commands

### ISSUE THREAD

**Issue by bigretromike** [japanesemediamanager/ShokoServer#621]
Are `POST` commands broken ? im talking about those that need parameters inside body and not inside url.

Like `/os/folder` because I couldn't test out those, because each time I tried it would not assign (Bind) values from body. It look like this could be affected after `async` migrate, but I'm not sure - maybe its on my end (fiddler) that's why I wanted to ask.

@da3dsoul @Cazzar ?

**Comment by da3dsoul** [comment]
File offset definitely works. It could be you, or it could be on a per endpoint basis

**Comment by bigretromike** [comment]
I ask wrong question probably. 

so if offset work then it work only with binding to object. then I need to ad model then.
