### ISSUE TITLE
Linux Branch - Fails to scan mergerfs mountpoint

### ISSUE THREAD

**Issue by Baine** [japanesemediamanager/ShokoServer#622]
## LOG FILE

[2017-05-18.txt](https://github.com/japanesemediamanager/ShokoServer/files/1010348/2017-05-18.txt)
process: launching shoko.cli.exe on linux host, connecting using shoko desktop
8956c7ba5dd57126410a91d1d0f2de3323d3884d

clicking on the folder icon of the mergerfs mountpoint to start import for that one, afterwards clicking on `run import`

## Description

I've got 3 import paths:

`/opt/Downloads/Ecchi/
/opt/Downloads/Hentai/_sorted/
/opt/Anime/`

`/opt/Downloads` and `/opt/Anime` are mountpoints for mergerfs volumes, utilizing the same drives.

exerpt of  `mount` command:
`Ani_I/Downloads:Ani_II/Downloads:Ani_III/Downloads:Tera_1/Disk_1/Downloads:Tera_2/Disk_2/Downloads:Tera_4/Disk_4/Downloads:Tera_5/Downloads:Tera_6/Downloads:Stor_I/Downloads on /opt/Downloads type fuse.mergerfs (rw,relatime,user_id=0,group_id=0,allow_other)
Ani_I/Anime:Ani_II/Anime:Ani_III/Anime:Tera_1/Disk_1/Anime:Tera_2/Disk_2/Anime:Tera_4/Disk_4/Anime:Tera_5/Anime:Tera_6/Anime:Stor_I/Anime on /opt/Anime type fuse.mergerfs (rw,relatime,user_id=0,group_id=0,allow_other)`

when adding the first two folders to shoko linux, import is working. it scans the folders, hashes and matches the files etc. all good.

once i add `/opt/Anime` as import folder, it ceases to work.

the log contains today's fresh start as well as clicking `run import` in shoko desktop as well as starting import for `/opt/Anime/` only.

Folder Structure (for all 3 Import folders):
`<import-folder>/<sub folder named by series>/<files named "series - epno - ep title.extension">`

## STEPS TO REPRODUCE

shokoserver, linux tree
775d574eeafa608c6ad95f403098e071b9f930a6

running on `Linux share 4.9.0-2-amd64 #1 SMP Debian 4.9.18-1 (2017-03-30) x86_64 GNU/Linux` 

mergerfs mounts as import folder (direct mountpoint as importfolder breaks it, subfolders as importfolder works)

click on `run import` or on the folder icon for the import folder, nothing happens

**Comment by Cazzar** [comment]
https://github.com/maxpiva/CloudFileSystem/pull/4

**Comment by Baine** [comment]
seems to be scanning and hashing, closed
