### ISSUE TITLE
Linux Tree - Issue with mediainfo

### ISSUE THREAD

**Issue by Baine** [japanesemediamanager/ShokoServer#623]
## LOG FILE

[2017-05-19.txt](https://github.com/japanesemediamanager/ShokoServer/files/1013353/2017-05-19.txt)

## Description

happens at multiple places
for example during startup or refreshing the "unknown files" view.

entry in log (example):
`08:39:25| --- Unable to read the media information of file /opt/Anime/Appleseed Saga Ex Machina/Appleseed Saga Ex Machina - 01 - Complete Movie.mkv ERROR: System.TypeInitializationException: The type initializer for 'Shoko.Server.FileHelper.MediaInfo.MediaConvert' threw an exception. ---> System.EntryPointNotFoundException: LoadLibraryEx
  at (wrapper managed-to-native) MediaInfoLib.MediaInfo:LoadLibraryEx (string,intptr,MediaInfoLib.MediaInfo/LoadLibraryFlags)
  at MediaInfoLib.MediaInfo..ctor () [0x0009b] in <27d036e3dabc4fbbae4ef2f4fa9d1f63>:0
  at Shoko.Server.FileHelper.MediaInfo.MediaConvert..cctor () [0x0000a] in <27d036e3dabc4fbbae4ef2f4fa9d1f63>:0
   --- End of inner exception stack trace ---
  at Shoko.Server.Models.SVR_VideoLocal_Place.RefreshMediaInfo () [0x0010c] in <27d036e3dabc4fbbae4ef2f4fa9d1f63>:0`

file (`/opt/Anime/Appleseed Saga Ex Machina/Appleseed Saga Ex Machina - 01 - Complete Movie.mkv`) does exist, is accessible and mediainfo linux and windows mediainfo show expected information

## STEPS TO REPRODUCE

775d574eeafa608c6ad95f403098e071b9f930a6

linux branch
running on `Linux share 4.9.0-2-amd64 #1 SMP Debian 4.9.18-1 (2017-03-30) x86_64 GNU/Linux`
mysql database

**Comment by Cazzar** [comment]
Try installing libMediaInfo

**Comment by Baine** [comment]
it's installed.

tried with libmediainfo0
as well as libmediainfo0v5

also install libmediainfo-dev just to be sure, to no avail.

**Comment by Baine** [comment]
added the following to Shoko.Server.dll.config
`<dllmap os="osx" dll="MediaInfo.dll" target="libmediainfo.0.dylib"/>
  <dllmap os="linux" dll="MediaInfo.dll" target="libmediainfo.so.0" />
  <dllmap os="freebsd" dll="MediaInfo.dll" target="libmediainfo.so.0" />
  <dllmap os="solaris" dll="MediaInfo.dll" target="libmediainfo.so.0.0.0" />`

[dll_debug.txt](https://github.com/japanesemediamanager/ShokoServer/files/1014946/dll_debug.txt)

**Comment by Cazzar** [comment]
Looks like the issue is libc

`Mono: DllImport error loading library '/usr/lib/libc.so.6': '/usr/lib/libc.so.6: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden'.`

**Comment by Baine** [comment]
strange thing is, that libc6 is installed.

`root@share:~/Release# find / -iname "libc.so.6"
/lib/x86_64-linux-gnu/libc.so.6
/lib32/libc.so.6
/libx32/libc.so.6

 libc6-i386/testing,now 2.24-10 amd64  [Installiert,automatisch]
libc6/testing,now 2.24-10 amd64  [installiert]`

i've created a link to the location the debug log complains about
`root@share:/usr/lib# ln /lib/x86_64-linux-gnu/libc.so.6 libc.so.6`
still no help :(
resulting log:
[dll_debug.txt](https://github.com/japanesemediamanager/ShokoServer/files/1015199/dll_debug.txt)

**Comment by Baine** [comment]
close because of a commit by @Cazzar
