### ISSUE TITLE
Sometimes renaming files result in placeholder being used

### ISSUE THREAD

**Issue by miracle152004** [japanesemediamanager/ShokoServer#632]
Sometimes the renaming results in the usage of placeholders instead of replacing them.
This results in the episodes being named : %ann_-_09[Weeb].mkv or something.

Last series where this happened was "The King`s Avatar".
The drop folder has the correct name, but the file does not.
Here the renaming script I used:
```
DO ADD %ann

DO ADD ' - %enr'

DO ADD [%grp]

// Replacement rules (cleanup)  
DO REPLACE ' ' '_' 

// replace spaces with underscores  
DO REPLACE '0x0' ''  
DO REPLACE '__' '_'  
DO REPLACE '__' '_'

// Replace all illegal file name characters  
DO REPLACE '<' '('   
DO REPLACE '>' ')'   
DO REPLACE ':' ''   
DO REPLACE '"' '`'  
DO REPLACE '/' ''  
DO REPLACE '\' '_'   
DO REPLACE '|' '_'   
DO REPLACE '?' '_'   
DO REPLACE '*' '_'
DO REPLACE ';' ''
DO REPLACE ';' ''
```

Could someone please take a look and tell me if there is an error in the application or in the renaming script.

Thanks.

Best regards miracle152004

**Comment by da3dsoul** [comment]
That looks like a Shoko issue, but I've never seen it before. The renamer is going to get an overhaul soon ™.

**Comment by da3dsoul** [comment]
Fixed
