### ISSUE TITLE
right click to open webui in windows taskbar.

### ISSUE THREAD

**Issue by CuddleBear92** [japanesemediamanager/ShokoServer#638]
a simple right click to open the webui in the windows taskbar.
adding ofc the new option over view Shoko server or close it.

side note, can it auto login with the default user when this feature is used?

**Comment by ElementalCrisis** [comment]
I thought I added the WebUI option when right-clicking? Must of forgot to push changes. :(

As for the auto-login, that is a WebUI issue, not Server issue. 

@hidden4003, have you added the login settings in WebUI yet?

**Comment by ElementalCrisis** [comment]
Done.

![image](https://user-images.githubusercontent.com/9443295/27946296-e8a7d7e2-62a5-11e7-8035-d1cd2036a522.png)

Commit will be up in a few minutes,
